<a href="https://colab.research.google.com/github/wiktorspryszynski/data-science-bootcamp/blob/main/01_introduction/01_numpy_intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Podstawy

In [ ]:
print('Hello Colab')

Hello Colab


In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.6'

In [10]:
x = np.array([1, 2, 3])
print(x)
print(type(x))

[1 2 3]
<class 'numpy.ndarray'>


In [11]:
x.ndim

1

In [12]:
x.shape

(3,)

In [13]:
x.size

3

In [14]:
x.dtype

dtype('int64')

In [15]:
y = np.array([[1, 2, 3], [4, 5, 6]])
y

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
print(y.ndim)

2


In [17]:
print(y.shape)

(2, 3)


In [18]:
print(y.size)

6


In [23]:
z = np.array(
    [[[4, 3, 1],
      [3, 1, 2]],
     
     [[4, 1, 3],
      [4, 2, 1]],
     
     [[3, 2, 1],
      [4, 3, 2]]]
)
z

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]],

       [[3, 2, 1],
        [4, 3, 2]]])

In [24]:
print(z.ndim)
print(z.shape)
print(z.size)

3
(3, 2, 3)
18


### Typy danych

In [25]:
A = np.array([1, 2, 3])
A.dtype

dtype('int64')

In [26]:
A = np.array([1.0, 2.3, 3.3])
A.dtype

dtype('float64')

In [27]:
A = np.array([1, 2, 3], dtype='float')
A.dtype

dtype('float64')

In [28]:
A = np.array([1, 2, 3], dtype='complex')
A.dtype

dtype('complex128')

In [29]:
A = np.array([1.0, 2.7, 3.3], dtype='int')
A.dtype

dtype('int64')

In [30]:
A = np.array([True, False])
A.dtype

dtype('bool')

### Tworzenie tablic

In [31]:
np.zeros(shape = (4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [32]:
np.zeros(shape = (4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [34]:
np.ones(shape=(5,5), dtype='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [35]:
np.full(shape=(3, 3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [38]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [39]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [42]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [43]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [44]:
np.linspace(start=0, stop=1, num=10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [46]:
A = np.arange(15)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [48]:
A.reshape((3, 5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [50]:
A.reshape((5, -1)) ### -1 używane jako znajdowanie odpowiedniej ilości kolumn do wierszy (lub na odwrót)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

### Operacje na tablicach

In [52]:
A = np.array([3, -1, 4, 2])
B = np.array([3, -1, 3, 2])
print(A)
print(B)

[ 3 -1  4  2]
[ 3 -1  3  2]


In [53]:
A + B

array([ 6, -2,  7,  4])

In [58]:
np.add(A, B)

array([ 6, -2,  7,  4])

In [54]:
A - B

array([0, 0, 1, 0])

In [60]:
np.subtract(A, B)

array([0, 0, 1, 0])

In [55]:
A * B

array([ 9,  1, 12,  4])

In [61]:
np.multiply(A, B)

array([ 9,  1, 12,  4])

In [56]:
A / B

array([1.        , 1.        , 1.33333333, 1.        ])

In [62]:
np.divide(A, B)

array([1.        , 1.        , 1.33333333, 1.        ])

In [57]:
A + 3

array([6, 2, 7, 5])

In [63]:
A - B*3

array([-6,  2, -5, -4])

In [65]:
X = np.array([[1, 3], [-2, 0]])
Y = np.array([[6, 0], [-1, 2]])
print(X)
print(Y)

[[ 1  3]
 [-2  0]]
[[ 6  0]
 [-1  2]]


In [66]:
X * Y

array([[6, 0],
       [2, 0]])

In [67]:
np.dot(X, Y) ### Mnożenie macierzy (to znane z algebry liniowej, nie mnożenie po macierzach)

array([[  3,   6],
       [-12,   0]])

In [68]:
X.dot(Y)

array([[  3,   6],
       [-12,   0]])

In [73]:
Y.dot(X) ### Mnożenie macierzy nie jest przemienne

array([[ 6, 18],
       [-5, -3]])

In [72]:
X @ Y ### To samo co dot

array([[  3,   6],
       [-12,   0]])

### Liczby pseudolosowe

In [75]:
np.random.seed(0)

In [76]:
np.random.randn()

1.764052345967664

In [77]:
np.random.randn(10)

array([ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799, -0.97727788,
        0.95008842, -0.15135721, -0.10321885,  0.4105985 ,  0.14404357])

In [78]:
np.random.randn(10, 4)

array([[ 1.45427351,  0.76103773,  0.12167502,  0.44386323],
       [ 0.33367433,  1.49407907, -0.20515826,  0.3130677 ],
       [-0.85409574, -2.55298982,  0.6536186 ,  0.8644362 ],
       [-0.74216502,  2.26975462, -1.45436567,  0.04575852],
       [-0.18718385,  1.53277921,  1.46935877,  0.15494743],
       [ 0.37816252, -0.88778575, -1.98079647, -0.34791215],
       [ 0.15634897,  1.23029068,  1.20237985, -0.38732682],
       [-0.30230275, -1.04855297, -1.42001794, -1.70627019],
       [ 1.9507754 , -0.50965218, -0.4380743 , -1.25279536],
       [ 0.77749036, -1.61389785, -0.21274028, -0.89546656]])

In [79]:
np.random.rand()

0.1965823616800535

In [80]:
np.random.rand(10)

array([0.36872517, 0.82099323, 0.09710128, 0.83794491, 0.09609841,
       0.97645947, 0.4686512 , 0.97676109, 0.60484552, 0.73926358])

In [81]:
np.random.rand(10, 2)

array([[0.03918779, 0.28280696],
       [0.12019656, 0.2961402 ],
       [0.11872772, 0.31798318],
       [0.41426299, 0.0641475 ],
       [0.69247212, 0.56660145],
       [0.26538949, 0.52324805],
       [0.09394051, 0.5759465 ],
       [0.9292962 , 0.31856895],
       [0.66741038, 0.13179786],
       [0.7163272 , 0.28940609]])

In [82]:
np.random.randint(10)

3

In [83]:
np.random.randint(low=10, high=101)

56

In [84]:
np.random.randint(low=10, high=101, size=10)

array([52, 66, 70, 87, 40, 34, 12, 13, 23, 50])

In [87]:
np.random.choice([4, 2, 1, 3, 5])

4

In [88]:
np.random.choice(['python', 'java', 'sql'])

'sql'

In [91]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
np.random.shuffle(data)
data

array([5, 3, 1, 4, 9, 0, 6, 7, 2, 8])

Podstawowe funkcje

In [98]:
np.exp(1)

2.718281828459045

In [99]:
np.sqrt(9)

3.0

In [100]:
np.all([2, 3, 1])

True

In [101]:
np.all([2, 3, 1, 0])

False

In [102]:
np.any([2, 3, 1])

True

In [104]:
np.any([0, 0, 0])

False

In [112]:
A = np.random.rand(5)
A

array([0.69742877, 0.45354268, 0.7220556 , 0.86638233, 0.97552151])

In [113]:
np.argmax(A) ### index najwiekszej wartości w tablicy

4

In [114]:
np.argmin(A)

1

In [116]:
np.argsort(A) ### Posortowane indeksy 

array([1, 0, 2, 3, 4])

In [117]:
np.max(A)

0.9755215050028858

In [118]:
np.min(A)

0.45354268267806885

In [119]:
np.mean(A)

0.7429861772448991

In [120]:
np.median(A)

0.7220555994703479

In [122]:
np.std(A) ## Odchylenie standardowe

0.17640316939720105

Indeksowanie i wycinanie

In [123]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [124]:
# A[idx], A[start:stop], A[:stop], A[start:]

In [125]:
A[2]

2

In [126]:
A[:2]

array([0, 1])

In [127]:
A[0:2]

array([0, 1])

In [128]:
A[[0, 2]]

array([0, 2])

In [129]:
A[-1]

19

In [131]:
A[10 : 15]

array([10, 11, 12, 13, 14])

In [134]:
A = A.reshape(4, -1)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [135]:
A[0]

array([0, 1, 2, 3, 4])

In [137]:
A[:, 0] ## Wycinanie kolumny

array([ 0,  5, 10, 15])

In [138]:
A[:, -2]

array([ 3,  8, 13, 18])

In [139]:
A[1, 2]

7

In [141]:
A[1:3, 1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

Iteracja po tablicach

In [142]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [143]:
for row in A:
  print(row)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [144]:
for row in A:
  print(row[:3])

[0 1 2]
[5 6 7]
[10 11 12]
[15 16 17]


In [145]:
for item in A.flat:
  print(item)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19


Zmiana rozmiaru tablic

In [146]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [147]:
A.shape

(4, 5)

In [148]:
A.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [149]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [153]:
A.T ## transponowanie - zamiana kolumn z wierszami

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2,  7, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

Maski logiczne

In [155]:
A = np.arange(start=-10, stop=10, step=0.5)
A

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [160]:
A = A.reshape(10, -1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [161]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [162]:
A[A > 0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [165]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [166]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [167]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [168]:
A[np.bitwise_or(A < -5, A > 5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])